# Generated by Django 4.0.4 on 2022-06-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_image'),
        ),
    ]
