# Generated by Django 4.0.4 on 2022-06-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='post_images'),
        ),
    ]
